sudo: required
dist: precise
language: ruby
rvm:
  - 1.9.3
services:
 - redis-server
before_install:
  - sudo apt-get install -qq libgeoip-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - gem update --system 1.8.25
  - bundle exec rake --trace db:test:load
  - export PREV_BUNDLE_GEMFILE=$BUNDLE_GEMFILE
  - export BUNDLE_GEMFILE=''
  - git clone --depth=100 --quiet git://github.com/allourideas/pairwise-api.git
  - cd ./pairwise-api
  - bundle install --local --binstubs
  - ./bin/rake db:create
  - ./bin/rake db:schema:load
  - ./bin/rake util:useradd[testing@dkapadia.com,wheatthins]
  - ./bin/rake util:useradd[photocracytest@dkapadia.com,saltines]
  - bundle exec ./script/server -p 4000 -d
  - cd ../
  - export BUNDLE_GEMFILE=$PREV_BUNDLE_GEMFILE
script: bundle exec rake test:functionals && bundle exec spec spec/integration spec/controllers/questions_controller_spec.rb && RAILS_ENV='cucumber' bundle exec cucumber --no-profile -f progress --require features --require lib features/[afiruvw]*
bundler_args: --local
