# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: aoi_web_development
  username: root
  password: bjahdh69
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

