# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: <%= ENV['AOI_MYSQL_DEV_DATABASE'] %>
  username: <%= ENV['AOI_MYSQL_USER'] %>
  password: <%= ENV['AOI_MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['AOI_MYSQL_HOST'] %>

production: &default
  adapter: mysql2
  database: <%= ENV['AOI_MYSQL_PRODUCTION_DATABASE'] %>
  username: <%= ENV['AOI_MYSQL_USER'] %>
  password: <%= ENV['AOI_MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['AOI_MYSQL_HOST'] %>

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

